SELECT * FROM USER_TABLES;

CREATE TABLE GENIE(
   GNUM INT PRIMARY KEY,
   TITLE VARCHAR(200) NOT NULL,
   ARTIST VARCHAR(200) NOT NULL,
   ALBUM VARCHAR(200) NOT NULL,
   VIEWNUM INT NOT NULL
);

CREATE TABLE MEMBER(
   MNUM INT PRIMARY KEY,
   MID VARCHAR(200) NOT NULL,
   MPW VARCHAR(200) NOT NULL,
   MNAME VARCHAR(200) NOT NULL
);

CREATE TABLE MYPAGE( 
   MYNUM INT PRIMARY KEY,
   GNUM INT NOT NULL,
   MEMBERNUM INT NOT NULL
   );
   
  

  
   
   
SELECT A.* FROM (SELECT RANK() OVER (ORDER BY VIEWNUM DESC), TITLE, ARTIST FROM (SELECT * FROM GENIE WHERE GNUM NOT IN(SELECT GNUM FROM MYPAGE) ORDER BY VIEWNUM DESC )  WHERE (ROWNUM BETWEEN 1 AND 5)  ORDER BY DBMS_RANDOM.RANDOM)A WHERE ROWNUM <= 5;


SELECT * FROM MYPAGE;
   
   
SELECT * FROM USER_TABLES;
DROP TABLE GENIE;
DROP TABLE MYPAGE;
DROP TABLE MEMBER;


SELECT * FROM GENIE;